### ISSUE TITLE
How do you "stop solution"

### ISSUE THREAD

**Issue by Seekatar** [Azure-Samples/iot-hub-c-m0wifi-getstartedkit#35]
You mention a few times in the tutorial to "stop your remote monitoring solution" or "stop your Command Center jobs"  to avoid charges.  Can you give directions for doing that?  The iot portal doesn't have a stop, and in Azure portal, I'm not sure what things to stop to avoid charges.  Thanks.

I stopped everything in the Azure portal for the group, and disabled all the devices, but the count on the event hub kept going up, so I deleted the solution (shouldn't there be a Stop button in addition to Delete?)

**Comment by hegate** [comment]
HI @Seekatar thanks for providing feedback. You may want to access the Stream Analytics jobs and also stop them. We don't have an all up "Stop" button for the Remote Monitoring solution yet, but we'll include more info on the tutorial on how to perform these steps shortly. Thanks!

**Comment by AttunixCorp** [comment]
Resolved in commit c4e24d0e97a18b5587af89be00f6f34356bbc7ba
