### ISSUE TITLE
Provisioning failed due to Bing Maps

### ISSUE THREAD

**Issue by Petezah** [Azure-Samples/iot-hub-c-m0wifi-getstartedkit#36]
I get "Bad Request - Error converting varchar to int" during Remote Monitoring provisioning.  There seems to be no clear way to mitigate.  Probably, I don't need Bing Maps to complete the tutorial on this page, but I'm also not sure what I'm missing out on either.

**Comment by hegate** [comment]
Hi @Petezah sounds like there's been an issue provisioning the remote monitoring solution. I'd encourage you to delete that solution and try re-provisioning. Let me know if that fixes it.

Thanks, 
H,
