### ISSUE TITLE
Missing WiFi101.h error

### ISSUE THREAD

**Issue by richardcornell** [Azure-Samples/iot-hub-c-m0wifi-getstartedkit#37]
Following the starter kit instructions for remote monitoring with the Adafruit Huzzah ESP8266 works until I compile the sketch at step 1.8 and the following error results:
C:\Users\<name>\Documents\Arduino\libraries\AzureIoT\src\util/HTTPSClient.h:4:21: fatal error: WiFi101.h: No such file or directory
#include <WiFi101.h>
Is there something missing from the instructions i.e. something else that needs to be installed as the file is not present on my PC. Adding the WiFi101 library to Arduino IDE (which is not mentioned in the instructions) causes more compilation errors.

**Comment by stefangordon** [comment]
Hey Richard, are you using the m0 sample (this repo) with the Huzzah, or the Huzzah sample/instructions?

**Comment by richardcornell** [comment]
I'm using the [https://github.com/Azure-Samples/iot-hub-c-huzzah-getstartedkit](url) sample and instructions.

**Comment by stefangordon** [comment]
Great.  Also verify you have the Huzzah selected from the board selection UI in your Arduino IDE - that is the most likely reason it would try to use the incorrect headers as they are selected in httpsclient.h based on the type of board you are compiling for.

**Comment by stefangordon** [comment]
Oh - Sorry Richard, I suspect these instructions were incorrect and led you to install the Azure IoT Library from the Arduino UI - this version looks to be not refreshed with the latest for the Huzzah yet.  You should remove the existing AzureIoT library with the library manager, and download the library from https://github.com/stefangordon/AzureIoT by cloning the repo, or just downloading it as zip from https://github.com/stefangordon/AzureIoT/archive/master.zip and placing the AzureIot folder in `C:\Program Files (x86)\Arduino\libraries` and restarting the IDE.

I'm working on getting this documentation updated right now.

**Comment by richardcornell** [comment]
The library manager doesn't appear to allow the uninstall of the AzureIoT library that's already there so I have copied the new AzureIoT folder into Program Files (x86)\Arduino\libraries and there are a load of compile errors starting with;
C:\Program Files (x86)\Arduino\libraries\AzureIoT\src\esp8266\libc_esp.c: In function 'fprintf':
C:\Program Files (x86)\Arduino\libraries\AzureIoT\src\esp8266\libc_esp.c:19:5: error: incompatible type for argument 2 of 'ets_vprintf'
     ret = ets_vprintf(format, arglist);

It ends by saying;
Multiple libraries were found for "AzureIoT.h"
 Used: C:\Program Files (x86)\Arduino\libraries\AzureIoT
 Not used: C:\Users\<name>\Documents\Arduino\libraries\AzureIoT

Unless you have any other suggestions I'll remove Arduino IDE and start again when I have time.

**Comment by stefangordon** [comment]
Next issue you might run into is the DHT22 remote monitoring sample in those instructions being outdated - I'm verifying that now.

**Comment by stefangordon** [comment]
Instructions and remote monitoring sample are updated in the quick start at https://github.com/Azure-Samples/iot-hub-c-huzzah-getstartedkit to reflect using the latest library and some tweaks to the .ino to be compatible.

**Comment by richardcornell** [comment]
I've updated the files and its all working fine now and I can see data from the sensors being displayed in the Azure IoT Suite dashboard! Huzzah! Thank you Stefan.

**Comment by stefangordon** [comment]
Perfect, thanks Richard.
