### ISSUE TITLE
Issues with arduino-libraries/AzureIoT zip

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure-Samples/iot-hub-c-m0wifi-getstartedkit#40]
Re:
https://github.com/Azure-Samples/iot-hub-c-m0wifi-getstartedkit/blob/master/README.md#16-install-library-dependencies

It points to downloading the library: "Download the library as a zip"
Which references:
https://github.com/arduino-libraries/AzureIoT/archive/master.zip

remote_monitoring.ino has a reference to:
#include <Adafruit_WINC1500MDNS.h>

Which does not exist in their library.  See: https://github.com/adafruit/Adafruit_WINC1500/tree/master/src

I tried to create a PR to fix this; however, I couldn't even find the repo for this lib.  Where does this source package come from?

Does that explain why the documentation references so many lines that needed to be modified?

**Comment by Ilias-Tsigkogiannis** [comment]
This has been fixed. Please reopen, if it is still not clear.
