### ISSUE TITLE
Cannot compile: fatal error: Adafruit_Sensor.h: No such file or directory

### ISSUE THREAD

**Issue by ralfr** [Azure-Samples/iot-hub-c-m0wifi-getstartedkit#42]
I‘m trying to get the sample compiled. However, I run into the following compile error:

file included from C:\Users\ralfr\Downloads\iot-hub-c-m0wifi-getstartedkit-master\iot-hub-c-m0wifi-getstartedkit-master\remote_monitoring\remote_monitoring.ino:4:0:

C:\Users\ralfr\Documents\Arduino\libraries\Adafruit_BME280_Library-master/Adafruit_BME280.h:26:29: fatal error: Adafruit_Sensor.h: No such file or directory

 #include <Adafruit_Sensor.h>

                             ^

compilation terminated.

Multiple libraries were found for "Adafruit_BME280.h"
 Used: C:\Users\ralfr\Documents\Arduino\libraries\Adafruit_BME280_Library-master
 Not used: C:\Users\ralfr\Documents\Arduino\libraries\Adafruit_BME280_Library
exit status 1
Error compiling for board Adafruit Feather M0 (Native USB Port).

I also could not find the Sensor Masters library. Please help!

**Comment by Michel-IT** [comment]
same error, same problem with this sensor

**Comment by Michel-IT** [comment]
try to add this library to me it worked, if you think it is so simple that such a question does not deserve an answer, lol

https://github.com/adafruit/Adafruit_Sensor

**Comment by sachendra003** [comment]
Download the "Adafruit Unified Sensor" library from the library manager - this worked for me.
 
![adafruit sensor header file](https://user-images.githubusercontent.com/31585105/56715860-73d99b00-6756-11e9-9aef-64cc77b4bac4.PNG)
![vlcsnap-2019-04-25-12h39m06s015_LI](https://user-images.githubusercontent.com/31585105/56716302-a2a44100-6757-11e9-892b-96ebcae5ad62.jpg)
