### ISSUE TITLE
Remote Monitoring Sample: unable to HTTPAPIEX_ExecuteRequest after a while

### ISSUE THREAD

**Issue by ralfr** [Azure-Samples/iot-hub-c-m0wifi-getstartedkit#43]
I've successfully managed to get the Remote Monitoring sample up and running with the Adafruit Feather M0 Kit. When I launch the demo on the Feather M0, it starts transmitting data which shows up in Azure IoT.

However, after approx. 25 or so successful transmits, the serial console shows the following log entries repeatedly:

```
***/Arduino/libraries/AzureIoTHub-master/src/sdk/iothubtransporthttp.c Func:DoEvent Line:1223 unable to HTTPAPIEX_ExecuteRequest
```

It does not recover from that fail state and eventually stops transmitting at all. Any idea?

**Comment by Ilias-Tsigkogiannis** [comment]
I cannot repro this problem. Could you retry using the latest code and reopen the issue, if it still repros?
